#!/usr/bin/env ruby

FILEDIR = File.dirname(__FILE__)
require "getoptlong"
require FILEDIR + "/ws-config"
require FILEDIR + "/deps/client_utils"
require FILEDIR + "/deps/ws_adapter"

#USAGE = "USAGE: ws-create-user -e <email> -p <password> -m <mobile> -n <name>" 

command_desc={"cmd"=>"create-user",
               "opts"=> { "email"=>["e",1,""],
                      "password"=>["p",1,""],
                      "mobile"=>["m",1,""],
                      "name"=>["n",1,""]}}

USAGE = Client_Utils.generate_usage(command_desc)

if ARGV[0] == "--help" or ARGV[0] == "-h"
	puts USAGE
	exit 0
end

opts = GetoptLong.new(
[ '--email', '-e', GetoptLong::REQUIRED_ARGUMENT ],
[ '--password', '-p', GetoptLong::REQUIRED_ARGUMENT ],
[ '--mobile', '-m', GetoptLong::REQUIRED_ARGUMENT ],
[ '--name', '-n', GetoptLong::REQUIRED_ARGUMENT ]
)

email = nil
password = nil
mobile = nil
name = nil

begin
  opts.each do |opt, arg|
    case opt
      when '--email'
        email = arg
      when '--password'
        password = arg
      when '--mobile'
        mobile = arg
      when '--name'
        name = arg
    end
  end
rescue GetoptLong::InvalidOption
  puts USAGE
  exit 1
rescue GetoptLong::MissingArgument
  puts  USAGE
  exit 1
end

if email.nil? or password.nil? or name.nil?
  puts USAGE
  exit 1
end

ws = WSAdapter.new()

puts "########"
resp = ws.create_user(email,password,name,mobile)

if resp.size == 0
  Client_Utils.print_msg("create_fail")	
  exit_code = 0
elsif resp.first["error"] != nil
  Client_Utils.print_reason(resp.first)
  exit_code = 4   
else 
  exit_code = Client_Utils.print_table(resp, WS_USER_DISPLAY, true)
end 

Client_Utils.print_msg("transaction_complete")
exit(exit_code)

