#!/usr/bin/env ruby

FILEDIR = File.dirname(__FILE__)
require "getoptlong"
require FILEDIR + "/ws-config"
require FILEDIR + "/deps/client_utils"
require FILEDIR + "/deps/ws_adapter"

#USAGE = "USAGE: ws-create-org -n <name> -t <org_type_id> -i <introduce>" 

command_desc={"cmd"=>"create-org",
               "opts"=> {"name"=>["n",1,""], 
               "org_type_id"=>["t",1,""],
               "introduce"=>["i",1,""]}}

USAGE = Client_Utils.generate_usage(command_desc)

if ARGV[0] == "--help" or ARGV[0] == "-h"
	puts USAGE
	exit 0
end

opts = GetoptLong.new(
[ '--name', '-n', GetoptLong::REQUIRED_ARGUMENT ],
[ '--org_type_id', '-t', GetoptLong::REQUIRED_ARGUMENT ],
[ '--introduce', '-i', GetoptLong::REQUIRED_ARGUMENT ]
)

name = nil
org_type_id = nil
intro = nil

begin
  opts.each do |opt, arg|
    case opt
      when '--name'
        name = arg
      when '--org_type_id'
        org_type_id = arg
      when '--introduce'
        intro = arg
    end
  end
rescue GetoptLong::InvalidOption
  puts USAGE
  exit 1
rescue GetoptLong::MissingArgument
  puts  USAGE
  exit 1
end

if name.nil? or org_type_id.nil?
  puts USAGE
  exit 1
end

ws = WSAdapter.new()

resp = ws.create_org(name,org_type_id,intro)

if resp.size == 0
  Client_Utils.print_msg("create_fail")	
  exit_code = 0
elsif resp.first["error"] != nil
  Client_Utils.print_reason(resp.first)
  exit_code = 4   
else 
  exit_code = Client_Utils.print_table(resp, WS_ORG_DISPLAY, true)
end 

Client_Utils.print_msg("transaction_complete")
exit(exit_code)

