#!/usr/bin/env ruby

FILEDIR = File.dirname(__FILE__)
require "getoptlong"
require FILEDIR + "/ws-config"
require FILEDIR + "/deps/client_utils"
require FILEDIR + "/deps/ws_adapter"

#USAGE = "USAGE: ws-follow-event -e <event_id> " 

command_desc={"cmd"=>"follow-event",
               "opts"=> {"event_id"=>["e",1,""]}}

USAGE = Client_Utils.generate_usage(command_desc)

if ARGV[0] == "--help" or ARGV[0] == "-h"
	puts USAGE
	exit 0
end

opts = GetoptLong.new(
[ '--event_id', '-e', GetoptLong::REQUIRED_ARGUMENT ]
)

event_id = nil

begin
  opts.each do |opt, arg|
    case opt
      when '--event_id'
        event_id = arg
    end
  end
rescue GetoptLong::InvalidOption
  puts USAGE
  exit 1
rescue GetoptLong::MissingArgument
  puts  USAGE
  exit 1
end

if event_id.nil?
  puts USAGE
  exit 1
end

ws = WSAdapter.new()

resp = ws.follow_event(event_id)

if resp.size == 0
  Client_Utils.print_msg("follow_fail")	
  exit_code = 0
elsif resp.first["error"] != nil
  Client_Utils.print_reason(resp.first)
  exit_code = 4   
else 
  Client_Utils.print_msg("follow_success")
  exit_code = 0
end 

Client_Utils.print_msg("transaction_complete")
exit(exit_code)

